### ISSUE TITLE
not in dart pub

### ISSUE THREAD

**Issue by namiwang** [aryzhov/flutter-timer-builder#1]
Hi,

Great widget here, do you mind publish it so we could directly reference it instead of copying the code around?

Thanks!

**Comment by aryzhov** [comment]
What do you mean? It's published as [timer_builder](https://pub.dev/packages/timer_builder). Let me know if if doesn't work for you.

**Comment by namiwang** [comment]
Oh there it is!

Can't believe it doesn't show in the search result for `flutter timer builder` (https://pub.dev/packages?q=flutter+timer+builder)

Sorry to bother!
