### ISSUE TITLE
What about an end param for periodic timer?

### ISSUE THREAD

**Issue by rockingdice** [aryzhov/flutter-timer-builder#2]
I'm now using this widget which is pretty handy. But I still have to write my own stateful widget to make a counter, it will end after some duration. I wish it can rebuild itself each second, but stop building after the end time point.

**Comment by rockingdice** [comment]
hmm just found the example is what I'm looking for.
Then I realize I can use another timer to achieve this.

**Comment by Firman95** [comment]
Do you mind to share the code the achieve this?
